# Test-only (!) compose file for the Bento reference service

services:
  reference:
    build:
      context: .
      dockerfile: dev.Dockerfile
    restart: no
    depends_on:
      - reference-db
    environment:
      - DATABASE_URI=postgres://ref_user:ref_password@reference-db:5432/ref_db
    ports:
      - "5055:5000"
    volumes:
      - $PWD:/reference
    command: /bin/bash -c '
      cd /reference && 
      /poetry_user_install_dev.bash && 
      pytest -svv --cov=bento_reference_service --cov-branch &&
      coverage html
      '
  reference-db:
    image: postgres:16
    restart: no
    environment:
      - POSTGRES_USER=ref_user
      - POSTGRES_PASSWORD=ref_password
      - POSTGRES_DB=ref_db
    expose:
      - 5432
