# Standalone compose file for testing or an example deployment of a standalone reference service instance

services:
  reference:
    build: .
    depends_on:
      - reference-db
    environment:
      - DATABASE_URI=postgres://reference-db:5432
    volumes:
      - ./data:/reference/bento_reference_service/data
    networks:
      - net_reference_es

  reference-db:
    image: postgres:16
    volumes:
      - ./pg_data:/usr/share/elasticsearch/data
    networks:
      - net_reference_es

networks:
  net_reference_es:
    driver: bridge
