# Standalone compose file for testing or an example deployment of a standalone reference service instance

services:
  reference:
    build: .
    depends_on:
      - reference_es
    environment:
      - ELASTICSEARCH_URL=http://reference_es:9200
    volumes:
      - ./data:/reference/bento_reference_service/data
    networks:
      - net_reference_es

  reference_es:
    image: elasticsearch:8.6.0
    environment:
      - node.name=reference_es
      - discovery.type=single-node
    volumes:
      - ./es_data:/usr/share/elasticsearch/data
    networks:
      - net_reference_es

networks:
  net_reference_es:
    driver: bridge
